// Code generated by go generate; DO NOT EDIT.

//go:generate go run generate_version.go

package version

// git version info
const Version = "testing"

// time this package was built (format: time.UnixDate)
const BuildTime = "Tue Aug 27 05:10:22 PDT 2019"
